import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Post from '../components/theme/plain/Post'

import { getPageData } from '../libs/cms/queries'

export const getStaticProps = async () => {
  const data = await getPageData()

  return {
    props: {
      data,
    },
  }
}

const Home: NextPage = (props) => {
  console.log(props)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Post title={'Post'} text={'Lorem ipsum'} image={'/images/img.png'} />
      <header>header</header>
      <main>main</main>
      <footer>footer</footer>
    </div>
  )
}

export default Home
